name: Restream to Youtube
on:
  workflow_dispatch:
    inputs:
      stream_url:
        description: 'Twitch Stream URL'
        required: true
        default: 'https://www.twitch.tv/smallant'
      timeout:
        description: 'timeout'
        required: true
        default: '3h'
      bitrate:
        description: 'Desired bitrate (e.g., 800k for 800 kb/s)'
        required: false
        default: '800k'

      resolution:
        description: 'Desired resolution (e.g., 1280x720)'
        required: false
        default: 'res:1280'

        
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Extract Stream Title
      id: extract-title
      run: echo "STREAM_TITLE=$(yt-dlp --get-title ${{ github.event.inputs.stream_url }})" >> $GITHUB_ENV

    - name: Sanitize Stream Title
      run: |
        echo "SANITIZED_TITLE=$(echo $STREAM_TITLE | sed 's/[":<>|*?\\/\r\n]//g')" >> $GITHUB_ENV

    - name: ls
      run: ls
      continue-on-error: true

    - name: Restream to Youtube
      run: python3 twitch_youtube_restream.py
      continue-on-error: true


